pub mod caesar_cipher;
pub mod xor;
pub mod russian_peasant;
pub mod rot_13;
// pub mod mean_median_mode;
pub mod factors;
pub mod pascal_triangle;
pub mod prime_check;
pub mod binary_search;
pub mod pi;
